Update photomenu

diff --git a/photomenu b/photomenu
--- a/photomenu
+++ b/photomenu
@@ -1,31 +1,32 @@
 #!/usr/bin/env bash
 
 # This is a menu-based script to consolidate and automate my photo processing workflow.
-# TODO wmenu/dmenu detection, replace notify cmd, more imgmgk cmds, better cleanup of dttg
+# TODO more imgmgk cmds, better cleanup of dttg, better cleanup in general
 
 FOLDER=~/pics # global folder with subdirs to be listed
 WATERMARK=~/watermark.png
-NOTIFY_CMD=$(which dunstify || which notify-send) # Use dunstify if available, otherwise fall back to notify-send
-# MENU_CMD=$()
+# Use dunstify if available, otherwise fall back to notify-send
+NOTIFYCMD=$(which dunstify || which notify-send) 
+MENUCMD=$(which wmenu || which dmenu)
 
 transfer () {
 
 mount() { # Check if the card is mounted
-		[ -d /mnt/sdcard/DCIM/ ] || $NOTIFY_CMD "Card not mounted."
+		[ -d /mnt/sdcard/DCIM/ ] || $NOTIFYCMD "Card not mounted."
 }
 
 unmount() { # Unmount card
-		sudo systemd-mount --unmount /mnt/sdcard && $NOTIFY_CMD "Card unmounted."
+		sudo systemd-mount --unmount /mnt/sdcard && $NOTIFYCMD "Card unmounted."
 }
 
 dt() { # Open darktable to import today's photos
-		sudo systemd-mount --unmount /mnt/sdcard && $NOTIFY_CMD "Card unmounted; opening Darktable"
+		sudo systemd-mount --unmount /mnt/sdcard && $NOTIFYCMD "Card unmounted; opening Darktable"
 		(darktable "$FOLDER$(date '+%b_%d')") &
 }
 
 postrun() { # Menu to select what I want to do after photos have been transferred
-		$NOTIFY_CMD "Photos have transferred."
-		choice=$(printf "Unmount card\\nOpen Darktable, unmount\\nDo nothing" | dmenu -c -l 3 -i -p "Photos have transferred: ")
+		$NOTIFYCMD "Photos have transferred."
+		choice=$(printf "Unmount card\\nOpen Darktable, unmount\\nDo nothing" | $MENUCMD -c -l 3 -i -p "Photos have transferred: ")
 		case "$choice" in
 				Unmount*) unmount;;
 				Open*) dt;;
@@ -35,7 +36,7 @@ postrun() { # Menu to select what I want to do after photos have been transferre
 
 auto() { # Transfer photos from SD card into a directory for today's date
 		[ -d /mnt/sdcard/DCIM/ ] || exit 0
-		$NOTIFY_CMD "Photo transfer starting..."
+		$NOTIFYCMD "Photo transfer starting..."
 
 		mkdir -p "$FOLDER$(date '+%b_%d')"
 		find /mnt/sdcard -type f -name "*.CR2" -exec mv -nv {} "$FOLDER$(date '+%b_%d')/" \; && postrun
@@ -70,21 +71,21 @@ FROM images AS i
 JOIN film_rolls AS f ON i.film_id = f.id
 WHERE i.id IN (SELECT imgid FROM selected_images)
 LIMIT 1; 
-" || dunstify 'Open Darktable and select an image!' && exit 0) # use -readonly to avoid any risk of db corruption
+" || $NOTIFYCMD 'Open Darktable and select an image!' && exit 0) # use -readonly to avoid any risk of db corruption
 
 if [[ -e ${IMGPATH::-4}.png ]]; then
-		dunstify "Opening ${IMGPATH::-4}.png in GIMP."
+		$NOTIFYCMD "Opening ${IMGPATH::-4}.png in GIMP."
 		gimp ${IMGPATH::-4}.png
 else
-		dunstify -t 3000 "Exporting ${IMGPATH::-4}.png..." && darktable-cli $IMGPATH ${IMGPATH::-4}.png && notify-send "${IMGPATH::-4}.png exported. Opening GIMP." && gimp ${IMGPATH::-4}.png
+		$NOTIFYCMD -t 3000 "Exporting ${IMGPATH::-4}.png..." && darktable-cli $IMGPATH ${IMGPATH::-4}.png && notify-send "${IMGPATH::-4}.png exported. Opening GIMP." && gimp ${IMGPATH::-4}.png
 fi
 }
 
 
 openfolder () { # fuzzy find a folder to open in Darktable
-		CHOICE=$(echo -e "TYPE PATH...\n$(command ls -t1 $FOLDER)" | dmenu -c -l 10 -i -p "Folder: ") || exit 0
+		CHOICE=$(echo -e "TYPE PATH...\n$(command ls -t1 $FOLDER)" | $MENUCMD -c -l 10 -i -p "Folder: ") || exit 0
 				case $CHOICE in
-						*TYPE*) PHOTODIR="$(echo "" | dmenu -c -p "󰄄 Open: " <&-)" || exit 0 ;;
+						*TYPE*) PHOTODIR="$(echo "" | $MENUCMD -c -p "󰄄 Open: " <&-)" || exit 0 ;;
 						*) PHOTODIR=$FOLDER$CHOICE ;;
 				esac
 
@@ -93,9 +94,9 @@ openfolder () { # fuzzy find a folder to open in Darktable
 
 
 viewfolder () { # quickview a folder in nsxiv
-		CHOICE=$(echo -e "TYPE PATH...\n$(command ls -t1 $FOLDER)" | dmenu -c -l 10 -i -p "Folder: ") || exit 0
+		CHOICE=$(echo -e "TYPE PATH...\n$(command ls -t1 $FOLDER)" | $MENUCMD -c -l 10 -i -p "Folder: ") || exit 0
 				case $CHOICE in
-						*TYPE*) PHOTODIR="$(echo "" | dmenu -c -p "󰍋 View: " <&-)" || exit 0 ;;
+						*TYPE*) PHOTODIR="$(echo "" | $MENUCMD -c -p "󰍋 View: " <&-)" || exit 0 ;;
 						*) PHOTODIR=$FOLDER$CHOICE ;;
 				esac
 
@@ -104,55 +105,55 @@ viewfolder () { # quickview a folder in nsxiv
 
 
 rmexif () { # exiftool's binary location may need to be explicitly called. check /usr/bin/vendor_perl 
-		PHOTODIR="$(echo "" | dmenu -c -p "󰉏 " <&-)" || exit 0
-		dunstify "Removing exif data in $PHOTODIR..." && exiftool -all= $PHOTODIR/*{png,jpg,jpeg} && dunstify "Exif data removed on png, jpg, and jpeg in $PHOTODIR!"
+		PHOTODIR="$(echo "" | $MENUCMD -c -p "󰉏 " <&-)" || exit 0
+		$NOTIFYCMD "Removing exif data in $PHOTODIR..." && exiftool -all= $PHOTODIR/*{png,jpg,jpeg} && $NOTIFYCMD "Exif data removed on png, jpg, and jpeg in $PHOTODIR!"
 }
 
 
 checkexif () { # quickly check exif counts as a litmus test of whether a folder was stripped
-		CHOICE=$(echo -e "TYPE PATH...\n$(command ls -t1 $FOLDER)" | dmenu -c -l 10 -i -p "󰉏 ") || exit 0
+		CHOICE=$(echo -e "TYPE PATH...\n$(command ls -t1 $FOLDER)" | $MENUCMD -c -l 10 -i -p "󰉏 ") || exit 0
 				case $CHOICE in
-						*TYPE*) PHOTODIR="$(echo "" | dmenu -c -p "󰉏 " <&-)" || exit 0 ;;
+						*TYPE*) PHOTODIR="$(echo "" | $MENUCMD -c -p "󰉏 " <&-)" || exit 0 ;;
 						*) PHOTODIR=$FOLDER$CHOICE ;;
 				esac
-		dunstify -t 5000 "Fetching exif counts..."
-		dunstify -t 10000 "$(for f in $PHOTODIR/*; do echo $(exiftool "$f" | wc -l) $f; done)"
+		$NOTIFYCMD -t 5000 "Fetching exif counts..."
+		$NOTIFYCMD -t 10000 "$(for f in $PHOTODIR/*; do echo $(exiftool "$f" | wc -l) $f; done)"
 }
 
 
 convpng () { # copy cr2 to png
-		PHOTODIR="$(echo "" | dmenu -c -p "󰉏 " <&-)" || exit 0
-		dunstify "Copying all cr2 to png in $PHOTODIR/pics..."
-		mkdir -p $PHOTODIR/png && mogrify -path $PHOTODIR/png -format png $PHOTODIR/*.CR2 && dunstify "Copied all cr2 to png in $PHOTODIR/png."
+		PHOTODIR="$(echo "" | $MENUCMD -c -p "󰉏 " <&-)" || exit 0
+		$NOTIFYCMD "Copying all cr2 to png in $PHOTODIR/pics..."
+		mkdir -p $PHOTODIR/png && mogrify -path $PHOTODIR/png -format png $PHOTODIR/*.CR2 && $NOTIFYCMD "Copied all cr2 to png in $PHOTODIR/png."
 }
 
 
 convjpg () { # convert png to jpg, overwriting orignal png
-		dunstify -u critical -t 5000 "will modify ORIGINAL images (esc to quit)"
-		PHOTODIR="$(echo "" | dmenu -c -p "󰉏 " <&-)" || exit 0
-		dunstify "Converting all png to jpg in $PHOTODIR..."
-		mogrify -format jpg $PHOTODIR/*.png && dunstify "Converted all png to jpg in $PHOTODIR."
+		$NOTIFYCMD -u critical -t 5000 "will modify ORIGINAL images (esc to quit)"
+		PHOTODIR="$(echo "" | $MENUCMD -c -p "󰉏 " <&-)" || exit 0
+		$NOTIFYCMD "Converting all png to jpg in $PHOTODIR..."
+		mogrify -format jpg $PHOTODIR/*.png && $NOTIFYCMD "Converted all png to jpg in $PHOTODIR."
 }
 
 
 downscale () { # copy and downscale filtered images in a dir by chosen %
-		PHOTODIR="$(echo "" | dmenu -c -p "󰉏 " <&-)" || exit 0
-		SIZE="$(echo "" | dmenu -c -p " images over size M? " <&-)" || exit 0
-		SCALE="$(echo "" | dmenu -c -p " scale %: " <&-)" || exit 0
-		dunstify "Downscaling png larger than $SIZE M to $SCALE%, to $PHOTODIR/downscale..."
-		mkdir -p $PHOTODIR/downscale && find $PHOTODIR -type f -iregex '.*\.\(png\|jpe\?g\)' -size +"$SIZE"M -exec mogrify -path $PHOTODIR/downscale -scale "$SCALE"% {} \; && dunstify "All images over $SIZE M downscaled."
+		PHOTODIR="$(echo "" | $MENUCMD -c -p "󰉏 " <&-)" || exit 0
+		SIZE="$(echo "" | $MENUCMD -c -p " images over size M? " <&-)" || exit 0
+		SCALE="$(echo "" | $MENUCMD -c -p " scale %: " <&-)" || exit 0
+		$NOTIFYCMD "Downscaling png larger than $SIZE M to $SCALE%, to $PHOTODIR/downscale..."
+		mkdir -p $PHOTODIR/downscale && find $PHOTODIR -type f -iregex '.*\.\(png\|jpe\?g\)' -size +"$SIZE"M -exec mogrify -path $PHOTODIR/downscale -scale "$SCALE"% {} \; && $NOTIFYCMD "All images over $SIZE M downscaled."
 }
 
 
 watermark () { # watermarks to a copied ".watermark" extension
-		PHOTODIR="$(echo "" | dmenu -c -p "󰉏 " <&-)" || exit 0
-		dunstify "Watermarking copies of all png, jpg, jpeg."
-		find $PHOTODIR -type f -iregex '.*\.\(png\|jpe\?g\)' -exec composite -compose multiply -gravity SouthWest -geometry +99+99 $WATERMARK {} {}.watermark \; && dunstify "Watermarked all images in $PHOTODIR."
+		PHOTODIR="$(echo "" | $MENUCMD -c -p "󰉏 " <&-)" || exit 0
+		$NOTIFYCMD "Watermarking copies of all png, jpg, jpeg."
+		find $PHOTODIR -type f -iregex '.*\.\(png\|jpe\?g\)' -exec composite -compose multiply -gravity SouthWest -geometry +99+99 $WATERMARK {} {}.watermark \; && $NOTIFYCMD "Watermarked all images in $PHOTODIR."
 }
 
 
 menu() {
-		CHOICE=$(printf " transfer photos\\n dt to gimp\\n󱞊 view folder\\n󰉒 open folder\\n󱔼 remove exif\\n󱕁 check exif\\n󰸭 cr2 to png\\n󰈥 png to jpg\\n󰶡 downscale\\n watermark\\n PLACEHOLDERS\\n󰄄 darktable\\n gimp" | dmenu -c -l 21 -i )
+		CHOICE=$(printf " transfer photos\\n dt to gimp\\n󱞊 view folder\\n󰉒 open folder\\n󱔼 remove exif\\n󱕁 check exif\\n󰸭 cr2 to png\\n󰈥 png to jpg\\n󰶡 downscale\\n watermark\\n PLACEHOLDERS\\n󰄄 darktable\\n gimp" | $MENUCMD -c -l 21 -i )
 		case "$CHOICE" in
 				**) transfer ;;
 				**) dttg ;;
